### ISSUE TITLE
Terminal Cursor block is not in the line

### ISSUE THREAD

**Issue by mcbabo** [bautistaaa/big-sir#3]
![grafik](https://user-images.githubusercontent.com/67439212/149198992-c76838f0-80da-4cc3-8270-e555869c95f0.png)

**Comment by bautistaaa** [comment]
interesting I cant repro, what browser are you using?

**Comment by DamianKocjan** [comment]
Found the same issue on firefox. You can fix it by removing `top: -17px` from cursor (only on firefox)

**Comment by bautistaaa** [comment]
any of you want to fix it 😅

**Comment by bautistaaa** [comment]
fixed by https://github.com/bautistaaa/big-sir/pull/4
